name: C/C++ QT5 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: fedora-latest

    steps:
    - uses: actions/checkout@v2
    - name: new folder
      run: mkdir taemp
    - name: enter folder
      run: cd taemp
    - name: cmake file
      run: ../cmake
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
